---

- name: Configure webserver with nginx
  hosts: webservers
  become: true
  gather_facts: false

  vars:
    tls_dir: /etc/nginx/ssl/
    key_file: nginx.key
    cert_file: nginx.crt
    conf_file: /etc/nginx/sites-available/default
    server_name: localhost

  handlers:
    - name: Restart nginx
      ansible.builtin.service:
        name: nginx
        state: restarted
      notify: Restart nginx

  tasks:
    - name: Ensure nginx is installed
      ansible.builtin.package:
        name: nginx
        update_cache: true
      notify: Restart nginx

    - name: Create directories for TLS certificates
      ansible.builtin.file:
        path: "{{ tls_dir }}"
        state: directory
        mode: '0750'
      notify: Restart nginx

    - name: Copy TLS files
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: "{{ tls_dir }}"
        mode: '0600'
      loop:
        - "{{ key_file }}"
        - "{{ cert_file }}"
      notify: Restart nginx

    - name: Manage nginx config template
      ansible.builtin.template:
        src: nginx.conf.j2
        dest: "{{ conf_file }}"
        mode: '0644'
      notify: Restart nginx

    - name: Enable configuration
      ansible.builtin.file:
        src: "{{ conf_file }}"
        dest: /etc/nginx/sites-enabled/default
        state: link

    - name: Install home page
      ansible.builtin.template:
        src: index.html.j2
        dest: /usr/share/nginx/html/index.html
        mode: '0644'
      notify: Restart nginx

    - name: Restart nginx
      ansible.builtin.meta: flush_handlers

    - name: "Test it! {{ test_url }}"
      vars:
        test_url: "https://{{ ansible_host }}/index.html"
      delegate_to: localhost
      become: false
      ansible.builtin.uri:
        url: "{{ test_url }}"
        validate_certs: false
        return_content: true
      register: this
      failed_when: "'Running on ' not in this.content"
      tags:
        - test
